# Generated by Django 3.2 on 2024-01-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LogInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('typing_speed', models.IntegerField()),
                ('captcha_complete', models.TimeField()),
                ('device', models.CharField(max_length=25)),
                ('OS', models.CharField(max_length=25)),
                ('risk_factor', models.FloatField()),
                ('user', models.ManyToManyField(to='api.UserModel')),
            ],
        ),
    ]
