# Generated by Django 3.2 on 2024-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='captcha_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='risk_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='time',
            field=models.IntegerField(),
        ),
    ]
