# Generated by Django 3.2 on 2024-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240105_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
