# Generated by Django 3.2 on 2024-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240105_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='captcha_complete',
            field=models.FloatField(default=0.0),
        ),
    ]
