# Generated by Django 3.2 on 2024-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loginmodel_captcha_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
