# Generated by Django 3.2 on 2024-01-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240105_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
